spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_boot_projects?currentSchema=etm_b4
    username: postgres
    password: Aziza@0201
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  banner:
    image:
      location: classpath:banner.txt
server:
  port: 8009